version: 2.1

jobs:
  configure_infrastructure: 
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["cf:8b:46:ed:e3:f9:13:20:4d:8e:e4:58:e0:08:9b:ea"] 
      - run:
          name: test connection
          command: |
            ssh ubuntu@3.235.50.197
workflows:
  myWorkflow:
    jobs:
      - configure_infrastructure